services:
  app:
    build: .
    container_name: banner-futebol
    restart: unless-stopped
    expose:
      - '3000'
    env_file:
      - .env.local
    volumes:
      - ./public/banners:/app/public/banners
      - ./public/assets:/app/public/assets
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - banner-net
      - minha_rede
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.banner.rule=Host(`bannerinforlozzi.alfplaytv.shop`)"
      - "traefik.http.routers.banner.entrypoints=websecure"
      - "traefik.http.routers.banner.tls.certresolver=letsencrypt"
      - "traefik.http.services.banner.loadbalancer.server.port=3000"
      - "traefik.docker.network=minha_rede"

  cron:
    build: .
    container_name: banner-cron
    command: npx tsx src/scripts/cron.ts
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - ./public/banners:/app/public/banners
      - ./public/assets:/app/public/assets
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - banner-net

networks:
  banner-net:
    driver: bridge
  minha_rede:
    external: true
